# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'armdeploy'
    subscriptionId: '1802f3f1-ef90-49e0-ab3f-55b9dc8208c8'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ARMDEPLOY'
    location: 'West Us'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/webapp/armdeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)/webapp/armparam.json'
    deploymentMode: 'Incremental'

